### ISSUE TITLE
Could not load host key: /etc/ssh/ssh_host_rsa_key

### ISSUE THREAD

**Issue by thelfensdrfer** [IMC3ofC/db2express-c.docker#12]
Errors:

```
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
```

I had to add `RUN /usr/bin/ssh-keygen -A` to the Dockerfile to create the necessary keys first.

**Comment by ngrodet** [comment]
Thanks

**Comment by SPLAYER-HD** [comment]
I have the same error in a docker with Weblogic 1036. It was working for almost 1 year and suddenly that error started to appear.
Someone found a solution
