### ISSUE TITLE
403 Forbidden for DB2EXPRESSC_URL

### ISSUE THREAD

**Issue by gxvigo** [IMC3ofC/db2express-c.docker#3]
Hi There, 
the link to DB2 binary is not working properly:
https://s3.amazonaws.com/db2-expc105-64bit-centos/v10.5fp5_linuxx64_expc.tar.gz

<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>54C442E2A144B7FA</RequestId><HostId>X9JRg2zosdqwz0R7DbHr5ebHKjX8HzK1wwSt3h9BeS9PtrbwVz1RLRW839hhWgMYxjy4Qfyeld4=</HostId></Error>

Cheers, Giovanni

**Comment by wzymaster** [comment]
@gxvigo  you are trying to build a new DB2 docker image ? The default one isn't work for now since IBM policy , so you can place it anywhere with URL link and replace with the default one to run it through.

**Comment by wzymaster** [comment]
@gxvigo  Please feel free to download DB2 express-C image from [IBM official site](http://www-01.ibm.com/software/data/db2/express-c/download.html)

**Comment by gxvigo** [comment]
Thanks.
I downloaded the file 'v10.5_linuxx64_expc.tar.gz' from the site you mentioned and put in a local http server (node) and then pointed from the Dockerfile.
It worked fine.

Maybe this should be more explicit in the instruction or Dockerfile.

Cheer
